// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW1QwT5N9LCgzcOmEQe8mgL2ss_MRPKqw',
    appId: '1:874664304500:web:4bdb532ab5962e1e555621',
    messagingSenderId: '874664304500',
    projectId: 'artfolio-6bbcd',
    authDomain: 'artfolio-6bbcd.firebaseapp.com',
    storageBucket: 'artfolio-6bbcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8VnJddTwqZvRpziA6Hy2ErwKS87S2LM',
    appId: '1:874664304500:android:15e0d459bcf43e5d555621',
    messagingSenderId: '874664304500',
    projectId: 'artfolio-6bbcd',
    storageBucket: 'artfolio-6bbcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtYtGR93bMd9uSkebrF2IL4C8I4p7jq9I',
    appId: '1:874664304500:ios:5f208069a2045f0a555621',
    messagingSenderId: '874664304500',
    projectId: 'artfolio-6bbcd',
    storageBucket: 'artfolio-6bbcd.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );
}
